### ISSUE TITLE
iOS Cannot Login

### ISSUE THREAD

**Issue by vmatsnev** [lukeweber/webrtc-jingle-client#87]
I have downloaded and build project successfully. But on both simulator and device I can't pass through Login.

Here is what I get in console:

logging ininitingVoiceClient::VoiceClient - new ClientSignalingThread client_signaling_thread_@(0x41700005)
ClientSignalingThread::ClientSignalingThread
VoiceClient::Login
LOGT [stun=(stun.l.google.com:19302),turn=()]
ClientSignalingThread::Login
ClientSignalingThread::OnMessage: MSG_LOGIN
ClientSignalingThread::LoginS
TXmppPump::TXmppPump
TXmppPump::DoLogin
TXmppPump::DoLogin - logging on
ClientSignalingThread::OnMessage: MSG_XMPP_STATE
Resolving addr in PhysicalSocket::Connect
OpenSSLAdapter::OnConnectEvent
ClientSignalingThread::OnMessage: MSG_XMPP_STATE
OpenSSLAdapter::OnCloseEvent(0)
ClientSignalingThread::OnXmppSocketClose: with state=0
ClientSignalingThread::OnMessage: MSG_XMPP_SOCKET_CLOSE

**Comment by lukeweber** [comment]
In libjingle.gyp comment out IOS_XMPP_FRAMEWORK. It's part of the branch
ios-xmppframework that hasn't yet made it to trunk because it still has
some small bugs.

Hopefully hai can finish it up soon :)

Make sure you're building the voiceclient target as well.

For device target add -Dtarget_arch=arm to the build command, have to
investigate why it doesn't just work, but haven't had time.

Also another error:

MainStoryboard.storyboard was not included in bundle here is fix
http://stackoverflow.com/questions/9113329/xcode-4-2-mainstoryboard-not-found

**Comment by vmatsnev** [comment]
"In libjingle.gyp comment out IOS_XMPP_FRAMEWORK. It's part of the branch
ios-xmppframework that hasn't yet made it to trunk because it still has
some small bugs."

This step helped. Thanks a lot).
